[package]
name = "pwasm-test"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>", "Alexey Frolov <frol.rage@gmail.com>"]

[dependencies.pwasm-std]
version = "0.5"
features = ["std"]

[dependencies.pwasm-ethereum ]
version = "0.1"
features = ["std"]

[dependencies]
pwasm-abi = { version = "0.1", features = ["std"] }
bigint = "4"
