[package]
name = "pwasm-test"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>", "Alexey Frolov <frol.rage@gmail.com>"]

[dependencies]
pwasm-abi = "0.1"

[dependencies.bigint]
version = "4.4"
default-features = false

[dependencies.pwasm-std]
version = "0.9"
default-features = false

[dependencies.pwasm-ethereum]
version = "0.5"
default-features = false

[features]
default = ["std"]
std = ["pwasm-std/std", "pwasm-ethereum/std", "pwasm-abi/std"]
